print(False)
print(True)
print(3 == 2)
print(4.5 > 4.105)
print(2 <= 4)
print(2 != 2)
print(True or False)
print(True and False)
print(False and False)
print(2 > 4 or 4 >= 2)
print(1 == 1 and 2 == 2)